### ISSUE TITLE
Param is Root which is slightly confusing. Calling functions should call root only whereas called ones should have param name as currentNode/ Node.

### ISSUE THREAD

**Issue by chapanduk** [abhivenkiabhi/Data-Structure-and-Algorithm#2]
https://github.com/abhivenkiabhi/Data-Structure-and-Algorithm/blob/b6946dfaa42f10b7bad49cc93cd318abf310690f/bst/GenericBST.java#L55

**Comment by abhivenkiabhi** [comment]
changed param name from root to node.
